name: Release Please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
      uses: oliv3340/reusable-workflows-node/.github/workflows/node-release.yml@v1.0.0
      secrets:
        release-secret: ${{secrets.RELEASE_PLEASE}}
